# Configuration for pan/tilt devices
# In Rodney index0 is for the head and index 1 is spare
servo:
  index0:
    pan:
      servo: 0          
    tilt:
      servo: 1
      flip_rotation: true
  index1:
    pan:
      servo: 2
    tilt:
      servo: 3
      
index0_pan_trim: 6
index0_tilt_trim: 12

